//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace подготовка
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbomaintenance
    {
        public Nullable<System.DateTime> date { get; set; }
        public string issues_found { get; set; }
        public string vending_machine_id { get; set; }
        public string full_name { get; set; }
        public string work_description { get; set; }
        public int id { get; set; }
    
        public virtual vending_machines vending_machines { get; set; }
    }
}
