//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace подготовка
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public string timestamp { get; set; }
        public string product_id { get; set; }
        public string total_price { get; set; }
        public string quantity { get; set; }
        public string payment_method { get; set; }
        public int id { get; set; }
    
        public virtual products product { get; set; }
    }
}
