//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace подготовка
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.vending_machines = new HashSet<vending_machines>();
        }
    
        public string email { get; set; }
        public string full_name { get; set; }
        public Nullable<bool> is_manager { get; set; }
        public Nullable<bool> is_engineer { get; set; }
        public string phone { get; set; }
        public string id { get; set; }
        public Nullable<bool> is_operator { get; set; }
        public string role { get; set; }
        public string image { get; set; }
        public string pasword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vending_machines> vending_machines { get; set; }
    }
}
