//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace подготовка
{
    using System;
    using System.Collections.Generic;
    
    public partial class vending_machines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vending_machines()
        {
            this.dbomaintenances = new HashSet<dbomaintenance>();
            this.products = new HashSet<products>();
        }
    
        public string serial_number { get; set; }
        public string name { get; set; }
        public string user_id { get; set; }
        public string rfid_cash_collection { get; set; }
        public string notes { get; set; }
        public string location { get; set; }
        public string work_mode { get; set; }
        public string rfid_loading { get; set; }
        public string model { get; set; }
        public string kit_online_id { get; set; }
        public string company { get; set; }
        public string payment_type { get; set; }
        public string critical_threshold_template { get; set; }
        public string service_priority { get; set; }
        public string manager { get; set; }
        public string status { get; set; }
        public string notification_template { get; set; }
        public string working_hours { get; set; }
        public string engineer { get; set; }
        public string id { get; set; }
        public string install_date { get; set; }
        public string place { get; set; }
        public string @operator { get; set; }
        public string technician { get; set; }
        public string last_maintenance_date { get; set; }
        public string rfid_service { get; set; }
        public string coordinates { get; set; }
        public string total_income { get; set; }
        public string timezone { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbomaintenance> dbomaintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products> products { get; set; }
    }
}
